# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ny0D_QkxJgivCUwN4ZVlfxY9ghdsEQca
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
# 
# # Load data
df = pd.read_csv("data academic.csv")
# 
prog_code_mapping = {
    'BCH': 'Biochemistry',
    'BLD': 'Building technology',
    'CEN': 'Computer Engineering',
    'CHE': 'Chemical Engineering',
    'CHM': 'Industrial Chemistry',
    'CIS': 'Computer Science',
    'CVE': 'Civil Engineering',
    'EEE': 'Electrical and Electronics Engineering',
    'ICE': 'Information and Communication Engineering',
    'MAT': 'Mathematics',
    'MCB': 'Microbiology',
    'MCE': 'Mechanical Engineering',
    'MIS': 'Management and Information System',
    'PET': 'Petroleum Engineering',
    'PHYE': 'Industrial Physics-Electronics and IT Applications',
    'PHYG': 'Industrial Physics-Applied Geophysics',
    'PHYR' : 'Industrial Physics-Renewable Energy'
}

df['Prog Short'] = df['Prog Code'].map(prog_code_mapping)

# -------------------------------
# Sidebar Filters
# -------------------------------
st.sidebar.header("🔍 Filter Data")

# Filter Program Studi
prog_codes = df['Prog Code'].dropna().unique()
selected_prog = st.sidebar.selectbox("Pilih Program Studi (Prog Code):", sorted(prog_codes))

# Filter Tahun Masuk
available_yog = sorted(df['YoG'].dropna().unique())
selected_yogs = st.sidebar.multiselect("Pilih Tahun Masuk (YoG):", available_yog, default=available_yog)

# -------------------------------
# Main Dashboard
# -------------------------------
st.title("🎓 Academic Dashboard")

# Filter Data
filtered_df = df[(df['Prog Code'] == selected_prog) & (df['YoG'].isin(selected_yogs))]

# Card: Total Mahasiswa
if 'ID No' in filtered_df.columns:
    total_students = filtered_df['ID No'].nunique()
    st.markdown(f"### 📇 Total Mahasiswa: `{total_students}`")
else:
    st.warning("Kolom 'ID No.' tidak ditemukan dalam data.")

# Bar Chart: Rata-rata CGPA
st.subheader("📊 Rata-rata CGPA Mahasiswa")

if 'YoG' in filtered_df.columns and 'CGPA' in filtered_df.columns:
    if not filtered_df.empty:
        avg_gpa = filtered_df.groupby('YoG')['CGPA'].mean()
        fig_bar, ax_bar = plt.subplots(figsize=(5, 3))
        avg_gpa.plot(kind='bar', color='skyblue', ax=ax_bar)
        ax_bar.set_ylabel("Rata-rata CGPA")
        ax_bar.set_xlabel("Tahun Masuk")
        ax_bar.set_title(f"Rata-rata CGPA ({selected_prog})", fontsize=10)
        st.pyplot(fig_bar)
    else:
        st.info("Tidak ada data untuk kombinasi filter.")
else:
    st.warning("Kolom 'YoG' atau 'CGPA' tidak ditemukan dalam data.")

# Pie Chart: Distribusi Gender
st.subheader("🧑‍🎓 Distribusi Gender Mahasiswa")

if 'Gender' in filtered_df.columns:
    gender_counts = filtered_df['Gender'].value_counts()
    if not gender_counts.empty:
        fig_pie, ax_pie = plt.subplots(figsize=(4, 4))
        ax_pie.pie(gender_counts, labels=gender_counts.index, autopct='%1.1f%%',
                   startangle=90, colors=['lightcoral', 'lightskyblue'], textprops={'fontsize': 9})
        ax_pie.axis('equal')
        st.pyplot(fig_pie)
    else:
        st.info("Tidak ada data gender pada filter ini.")
else:
    st.warning("Kolom 'Gender' tidak ditemukan dalam data.")
